name: Build pages
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3

      - name: Inject environment secret
        run: |
          sed -i "s|{{MSG_URL}}|${{secrets.msg_url}}|g" index.html

      - name: Deploy
        uses: actions/upload-pages-artifact@v4
        with:
          path: .
      - uses: actions/deploy-pages@v4
